CG_noise: 0.003
n_gens: 1
solver: 'euler_ff'
stride: 1
check_clash: false
check_bonds: false
check_div: false
mask_prior: false
retain_AA: false
tolerance: 3e-5
nsteps: 100
system: 'pro'
save_dir: ''
external: false
vram: 32
save_traj: false
save_dcd: false
overwrite: false
t_flip: 0.2
type_flip: 'ref-ter'
